version: "3"

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx/conf:/etc/nginx/conf.d"
      - "./nginx/log:/var/log/nginx"
      - "./php:/var/www/html"

  db:
    container_name: db
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:11-alpine

  phpfpm:
    build:
      context: ./php
    user: "1000:1000"
    restart: unless-stopped
    volumes:
      - "./php:/var/www/html"
    depends_on:
      - db
